$lat
$lng
$lokasi_bencana
$kecamatan
$jenis_bencana
$nm_bencana
$inten_kejadian
$waktu
$tgl_kejadian
$sarana_umum
$ket_umum        
$meninggal       
$lk_ringan       
$lk_berat        
$hilang          
$rm_hancur       
$rm_ringan       
$rm_berat       
$akses_jalan     
$akses_jembatan  
$akses_transport 
$ket_rusak       
$pengungsian     
$almt_pengungsi  
$pengungsi_l     
$pengungsi_p     
$nm_kontak       
$hp_kontak       
$jab_kontak      
$ket_pengungsi   
$tmbh_keb1       
$tmbh_keb2       
$tmbh_keb3       
$tmbh_keb4       
$tmbh_keb5       
$jml_keb1        
$jml_keb2        
$jml_keb3        
$jml_keb4        
$jml_keb5        
$ket_keb